export const products = [
  {
    id: 1,
    name: "Wireless Bluetooth Headphones",
    description: "High-quality over-ear headphones with noise cancellation.",
    price: 129.99,
    category: "Electronics",
    brand: "Sony",
    stock: 25,
    rating: 4.5,
    image:
      "https://img.drz.lazcdn.com/static/pk/p/97735c81521d736281c3236a7bbe7f15.jpg_720x720q80.jpg",
  },
  {
    id: 2,
    name: "Smart LED TV 42 inch",
    description: "4K UHD Smart TV with built-in apps and voice control.",
    price: 399.99,
    category: "Electronics",
    brand: "Samsung",
    stock: 12,
    rating: 4.7,
    image: "https://static-01.daraz.pk/p/0e485a320ee5499164d898884ae0e86a.jpg",
  },
  {
    id: 3,
    name: "Running Shoes - Men's",
    description: "Lightweight running shoes for comfort and performance.",
    price: 89.99,
    category: "Footwear",
    brand: "Nike",
    stock: 30,
    rating: 4.3,
    image:
      "https://hips.hearstapps.com/hmg-prod/images/mhl-opener-run-shoes-311-67edd9f20e75a.jpg?crop=0.655xw:0.983xh;0.168xw,0&resize=1120:*",
  },
  {
    id: 4,
    name: "Stainless Steel Water Bottle",
    description: "Insulated 500ml bottle to keep your drinks hot or cold.",
    price: 19.99,
    category: "Accessories",
    brand: "Hydro Flask",
    stock: 50,
    rating: 4.8,
    image:
      "https://img.drz.lazcdn.com/static/pk/p/f2f017c3a1569b55ac6c99328a233bac.jpg_720x720q80.jpg",
  },
  {
    id: 5,
    name: "Gaming Mouse with RGB Lighting",
    description: "Ergonomic gaming mouse with customizable DPI and colors.",
    price: 49.99,
    category: "Gaming",
    brand: "Razer",
    stock: 18,
    rating: 4.6,
    image:
      "https://img.drz.lazcdn.com/static/pk/p/79361435810297f6aebac8cabe66545f.jpg_720x720q80.jpg",
  },
  {
    id: 6,
    name: "Office Ergonomic Chair",
    description: "Mesh backrest and adjustable height for all-day comfort.",
    price: 159.99,
    category: "Furniture",
    brand: "Herman Miller",
    stock: 10,
    rating: 4.9,
    image: "https://offisits.com.pk/wp-content/uploads/2024/09/a-3.jpeg",
  },
  {
    id: 7,
    name: "Cotton T-Shirt - Unisex",
    description: "Soft and breathable T-shirt for everyday wear.",
    price: 14.99,
    category: "Clothing",
    brand: "H&M",
    stock: 75,
    rating: 4.2,
    image:
      "https://neutral.com/cdn/shop/products/T61001_WHI_46640183-b2c8-40f2-bcf6-84e2bc4b9e23_1024x1024.jpg?v=1740048718",
  },
  {
    id: 8,
    name: "Digital SLR Camera",
    description: "24MP DSLR camera for stunning photography and videos.",
    price: 699.99,
    category: "Electronics",
    brand: "Canon",
    stock: 8,
    rating: 4.7,
    image:
      "https://utgadgets.com/cdn/shop/files/Canon_400D_DSLR_Camera_with_28-80mm_lens_-_Best_Price_in_Pakistan.jpg?v=1737635269",
  },
  {
    id: 9,
    name: "Portable Power Bank 10000mAh",
    description: "Charge your phone on the go with dual USB ports.",
    price: 24.99,
    category: "Accessories",
    brand: "Anker",
    stock: 60,
    rating: 4.4,
    image: "https://m.media-amazon.com/images/I/318KyawV5yL._SL500_.jpg",
  },
  {
    id: 10,
    name: "Laptop Backpack",
    description: "Water-resistant backpack with USB charging port.",
    price: 39.99,
    category: "Bags",
    brand: "Targus",
    stock: 40,
    rating: 4.5,
    image: "https://m.media-amazon.com/images/I/717Rp03xdmL._AC_SL1500_.jpg",
  },
  {
    id: 11,
    name: "Wireless Keyboard and Mouse Combo",
    description: "Quiet typing and ergonomic mouse for daily productivity.",
    price: 54.99,
    category: "Electronics",
    brand: "Logitech",
    stock: 20,
    rating: 4.6,
    image:
      "https://logitech.onlinesalestore.pk/cdn/shop/products/logitech-mk275-black-blue-wireless-keyboard-_-mouse-combo-03-logitech-pakistan.jpg?v=1639653562",
  },
  {
    id: 12,
    name: "Table Lamp with USB Port",
    description: "Modern lamp with adjustable brightness and USB charging.",
    price: 29.99,
    category: "Home Decor",
    brand: "Philips",
    stock: 35,
    rating: 4.3,
    image:
      "https://www.ubuy.com.pk/productimg/?image=aHR0cHM6Ly9tLm1lZGlhLWFtYXpvbi5jb20vaW1hZ2VzL0kvNjFzN1JHUndTb0wuX0FDX1NMMTUwMF8uanBn.jpg",
  },
  {
    id: 13,
    name: "Yoga Mat - Non Slip",
    description: "6mm thick mat ideal for yoga, pilates and home workouts.",
    price: 25.99,
    category: "Fitness",
    brand: "Adidas",
    stock: 45,
    rating: 4.4,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSkmbXe15cU-6xZMEs0juCQHnBNmsvrQE9Kw&s",
  },
  {
    id: 14,
    name: "Classic Analog Watch - Men's",
    description: "Elegant timepiece with leather strap and water resistance.",
    price: 89.99,
    category: "Watches",
    brand: "Fossil",
    stock: 22,
    rating: 4.5,
    image:
      "https://fossil.scene7.com/is/image/FossilPartners/FS6096_main?$sfcc_fos_large$",
  },
  {
    id: 15,
    name: "Blender with Glass Jar",
    description: "500W blender ideal for smoothies, sauces, and soups.",
    price: 59.99,
    category: "Kitchen",
    brand: "NutriBullet",
    stock: 28,
    rating: 4.6,
    image:
      "https://i5.walmartimages.com/seo/Mainstays-Glass-Jar-5-Speed-Blender-with-6-Cup-Jar-48Oz-Capacity-New_5c5ecb7d-7d62-4c07-a443-de507225735d.f6e3ddf3df6943060d4ad3d76c7ac62f.jpeg",
  },
  {
    id: 16,
    name: "Gaming Keyboard - Mechanical RGB",
    description: "Tactile mechanical keys with customizable backlight.",
    price: 74.99,
    category: "Gaming",
    brand: "Corsair",
    stock: 14,
    rating: 4.7,
    image:
      "https://img.drz.lazcdn.com/static/pk/p/bc894fef47f08e8631e0dbc1867d2352.jpg_720x720q80.jpg",
  },
  {
    id: 17,
    name: "Baby Diapers - Size M (50 pcs)",
    description: "Soft, breathable, and super absorbent baby diapers.",
    price: 29.99,
    category: "Baby Care",
    brand: "Pampers",
    stock: 100,
    rating: 4.5,
    image:
      "https://images.deliveryhero.io/image/darsktores-pk/6930862718949_01.jpg?height=480",
  },
  {
    id: 18,
    name: "LED String Lights (20ft)",
    description: "Decorative fairy lights with warm white glow for rooms.",
    price: 15.99,
    category: "Home Decor",
    brand: "Generic",
    stock: 0,
    rating: 4.2,
    image:
      "https://img.drz.lazcdn.com/static/pk/p/e5b809407d8eb3995103dd7d1dd44a72.jpg_720x720q80.jpg",
  },
  {
    id: 19,
    name: "Pet Food - Chicken Flavor 5kg",
    description: "Complete dry food for adult dogs, rich in protein.",
    price: 34.99,
    category: "Pet Supplies",
    brand: "Pedigree",
    stock: 25,
    rating: 4.4,
    image:
      "https://newparadisestore.com/cdn/shop/files/10192170-Pedigree-Adult-Chicken-and-Vegetables-Dry-Dog-Food-1.5kg-FRONT_480x480_6e6190e4-1c98-4315-866f-322fabb59b13.webp?v=1699969579",
  },
  {
    id: 20,
    name: "Digital Alarm Clock",
    description: "LED display, snooze feature, and adjustable brightness.",
    price: 22.99,
    category: "Electronics",
    brand: "Casio",
    stock: 38,
    rating: 4.3,
    image: "https://icasiostore.pk/wp-content/uploads/2024/05/DQ-750F-7.webp",
  },
];
